### ISSUE TITLE
Keyerror: 'active'

### ISSUE THREAD

**Issue by groupe3sun** [pyToshka/wazuh-prometheus-exporter#17]
I missed something or i have a really issue ?

**Comment by pyToshka** [comment]
Hello please provide your version of wazuh server

**Comment by groupe3sun** [comment]
Version 4.4.5

**Comment by pyToshka** [comment]
At this moment, version is not supporting by exporter

**Comment by groupe3sun** [comment]
Ok thx

**Comment by pyToshka** [comment]
fixed
