### ISSUE TITLE
Prometheus error

### ISSUE THREAD

**Issue by mark260486** [pyToshka/wazuh-prometheus-exporter#3]
Hi, Yuriy! Hope you doing well!

I tried to use your Wazuh exporter for Prometheus and face with the next error in Prometheus targets: `expected equal, got "INVALID"`.

I checked HTTP response from exporter and it provides metrics as it should be. Could you please help with that problem?

![running_exporter](https://user-images.githubusercontent.com/49118755/141330631-0b113659-9513-43b3-8bcb-8504ffac7d28.png)

![curl_to_exporter_instance](https://user-images.githubusercontent.com/49118755/141330511-9b998b2e-f8f1-49ba-a96b-2ffa63f023cc.png)

![prometheus_error](https://user-images.githubusercontent.com/49118755/141332801-66e6144c-6d42-4aca-bfd2-4686669056dd.png)

**Comment by pyToshka** [comment]
Hi @mark260486 , could you please check metrics via promtool and share result

**Comment by mark260486** [comment]
Hi! Thanks for reply!
There is result of promtool check

![screenshot](https://user-images.githubusercontent.com/49118755/141433891-9249c947-c1f7-4c42-8abd-aff38a006b6d.png)

**Comment by pyToshka** [comment]
@mark260486  could you please share you metrics? For me mostly interesting line 58

**Comment by mark260486** [comment]
Sure.
58 `last_registered_agent_info{wazuh-worker-build="17763"} 1.0`
59 `last_registered_agent_info{wazuh-worker-major="10"} 1.0`

As i understand problem could be in Wazuh worker naming?

**Comment by pyToshka** [comment]
@mark260486  could you please check last image from https://hub.docker.com/r/kennyopennix/wazuh-exporter

**Comment by mark260486** [comment]
Unfortunately, error is the same

**Comment by mark260486** [comment]
I was able to resolve the error commenting lines 101-109 in `main.py`. Now it works. I will try to find workaround, or smth like that. Thanks for your time :)

**Comment by pyToshka** [comment]
@mark260486  did you pull image without cache? 
Because for latest tag i fixed 3h ago

**Comment by mark260486** [comment]
Yay, it works! Thanks a lot :+1:
