### ISSUE TITLE
KeyError: 'data'

### ISSUE THREAD

**Issue by nzubarev122** [pyToshka/wazuh-prometheus-exporter#7]
Hello. Cant start Wazuh prometheus exporter

 docker run f14a43a90f21                
Starting Wazuh prometheus exporter
Traceback (most recent call last):
  File "./main.py", line 135, in <module>
    REGISTRY.register(WazuhCollector())
  File "/usr/local/lib/python3.8/site-packages/prometheus_client/registry.py", line 26, in register
    names = self._get_names(collector)
  File "/usr/local/lib/python3.8/site-packages/prometheus_client/registry.py", line 66, in _get_names
    for metric in desc_func():
  File "./main.py", line 118, in collect
    nodes = wazuh_connection.wazuh_get_nodes_healtchecks(auth)
  File "/app/wazuh/__init__.py", line 154, in wazuh_get_nodes_healtchecks
    return response.json()["data"]["affected_items"]
KeyError: 'data'

{"data": {"title": "Wazuh API REST", "api_version": "4.2.6", "revision": 40221, "license_name": "GPL 2.0", "license_url": "https://github.com/wazuh/wazuh/blob/4.2/LICENSE", "hostname": "wazuhru-app01a.", "timestamp": "2022-07-14T10:33:16+0000"}

Please help.

**Comment by pyToshka** [comment]
@nzubarev122 
Could you please share your configurations?
I couldnt reproduce for my local environment.
```
# HELP python_gc_objects_collected_total Objects collected during gc
# TYPE python_gc_objects_collected_total counter
python_gc_objects_collected_total{generation="0"} 280.0
python_gc_objects_collected_total{generation="1"} 76.0
python_gc_objects_collected_total{generation="2"} 0.0
# HELP python_gc_objects_uncollectable_total Uncollectable object found during GC
# TYPE python_gc_objects_uncollectable_total counter
python_gc_objects_uncollectable_total{generation="0"} 0.0
python_gc_objects_uncollectable_total{generation="1"} 0.0
python_gc_objects_uncollectable_total{generation="2"} 0.0
# HELP python_gc_collections_total Number of times this generation was collected
# TYPE python_gc_collections_total counter
python_gc_collections_total{generation="0"} 52.0
python_gc_collections_total{generation="1"} 4.0
python_gc_collections_total{generation="2"} 0.0
# HELP python_info Python platform information
# TYPE python_info gauge
python_info{implementation="CPython",major="3",minor="8",patchlevel="6",version="3.8.6"} 1.0
# HELP wazuh_total_agent Total Wazuh agents count
# TYPE wazuh_total_agent summary
# HELP wazuh_total_group Total Wazuh groups count
# TYPE wazuh_total_group summary
wazuh_agents_group 0.0
# HELP wazuh_agent_status Total Wazuh agents by status
# TYPE wazuh_agent_status summary
wazuh_active_agents 0.0
wazuh_disconnected_agents 0.0
wazuh_never_connected_agents 0.0
wazuh_pending_agents 0.0
wazuh_total_agents 0.0
# HELP wazuh_agent_version_info Wazuh agent versions
# TYPE wazuh_agent_version_info gauge
# HELP last_registered_agent_info Wazuh last registered agent
# TYPE last_registered_agent_info gauge
# HELP nodes_healthcheck_info Wazuh nodes healthcheck
# TYPE nodes_healthcheck_info gauge
nodes_healthcheck_info{name="wazuh-manager-master"} 1.0
nodes_healthcheck_info{type="master"} 1.0
nodes_healthcheck_info{version="4.2.6"} 1.0
nodes_healthcheck_info{ip="wazuh-manager-master-0.wazuh-cluster.wazuh"} 1.0
nodes_healthcheck_info{n_active_agents="1"} 1.0
nodes_healthcheck_info{name="wazuh-manager-worker-0"} 1.0
nodes_healthcheck_info{type="worker"} 1.0
nodes_healthcheck_info{version="4.2.6"} 1.0
nodes_healthcheck_info{ip="10.1.0.130"} 1.0
nodes_healthcheck_info{n_active_agents="0"} 1.0
# HELP wazuh_api_info Wazuh API information
# TYPE wazuh_api_info gauge
wazuh_api_info{title="Wazuh API REST"} 1.0
wazuh_api_info{api_version="4.2.6"} 1.0
wazuh_api_info{revision="40221"} 1.0
wazuh_api_info{license_name="GPL 2.0"} 1.0
wazuh_api_info{license_url="https://github.com/wazuh/wazuh/blob/4.2/LICENSE"} 1.0
wazuh_api_info{hostname="wazuh-manager-master-0"} 1.0
wazuh_api_info{timestamp="2022-07-15T05:21:23+0000"} 1.0
```

**Comment by pyToshka** [comment]
@nzubarev122 Hi, unfortunately i didnt get response feel free to re-open issue

**Comment by badhop** [comment]
Hi, I have the same issue, using latest wazuh-exporter:
`Traceback (most recent call last):
  File "./main.py", line 528, in <module>
    REGISTRY.register(WazuhCollector())
  File "/usr/local/lib/python3.8/site-packages/prometheus_client/registry.py", line 40, in register
    names = self._get_names(collector)
  File "/usr/local/lib/python3.8/site-packages/prometheus_client/registry.py", line 80, in _get_names
    for metric in desc_func():
  File "./main.py", line 151, in collect
    nodes = wazuh_connection.wazuh_get_nodes_healtchecks(auth)
  File "/app/wazuh/__init__.py", line 250, in wazuh_get_nodes_healtchecks
    return response.json()["data"]["affected_items"]
KeyError: 'data'`

**Comment by tdicknet** [comment]
@badhop I guess you use a single server wazuh setup, right? I commented out the lines around 151 which requests a cluster endpoint.

**Comment by pyToshka** [comment]
Please for any new issues create new issue with full description and provide all configuration for Your environment
